[programs.localnet]
sigma = "651wt9EAWKaaxxLcmD9APKa8FuYZXhtgbds8DM4UGYRM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/hadi/.config/solana/hadi.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
